name: Auto approve

on: pull_request_target

permissions:
  contents: read
  pull-requests: write

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ github.token }}
          review-message: Dependabot PR approved

